#!/bin/sh

# make sure we are in "project" directory
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH/project

echo "PROMPT=\"Hi universe\"
print(PROMPT)">test.py

git add .
git commit -m "Fixed merge conflict"

git log --graph --oneline --all

echo "\n5. Fixed merge conflict by combining the changes."